# Generated by Django 4.0.2 on 2022-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='adopciones')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('tipo_animal', models.CharField(choices=[('Perros', 'Perros'), ('Gatos', 'Gatos'), ('Aves', 'Aves'), ('Roedores', 'Roedores'), ('Otros', 'Otros')], max_length=50)),
            ],
        ),
    ]
