# Generated by Django 4.0.2 on 2022-06-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
